version: '3.8'

services:
  {{ odoo_service_name }}:
    image: odoo:13.0
    container_name: {{ odoo_container_name }}
    depends_on:
      - {{ odoo_db_service_name }}
    ports:
      - "{{ odoo_port }}:8069"
    environment:
      - HOST={{ odoo_db_service_name }}
      - USER={{ odoo_db_user }}
      - PASSWORD={{ odoo_db_password }}
    volumes:
      - {{ odoo_data_volume }}:/var/lib/odoo
    networks:
      - {{ odoo_network_name }}

  {{ odoo_db_service_name }}:
    image: postgres:13
    container_name: {{ odoo_db_container_name }}
    environment:
      POSTGRES_USER: {{ odoo_db_user }}
      POSTGRES_PASSWORD: {{ odoo_db_password }}
      POSTGRES_DB: {{ odoo_db_name }}
    volumes:
      - {{ odoo_db_volume }}:/var/lib/postgresql/data
    networks:
      - {{ odoo_network_name }}

volumes:
  {{ odoo_data_volume }}:
  {{ odoo_db_volume }}:

networks:
  {{ odoo_network_name }}:

