- name: Pull Odoo Docker image
  docker_image:
    name: "kenyblader/odoo"
    tag: "{{ version }}"
    source: pull

- name: Run Odoo container
  docker_container:
    name: odoo
    image: "kenyblader/odoo:{{ version }}"
    state: started
    ports:
      - "8069:8069"
    volumes:
      - "{{ odoo_data_path }}:/var/lib/odoo"

