- name: Pull pgAdmin Docker image
  docker_image:
    name: "kenyblader/pgadmin"
    tag: "{{ version }}"
    source: pull

- name: Run pgAdmin container
  docker_container:
    name: pgadmin
    image: "kenyblader/pgadmin:{{ version }}"
    state: started
    ports:
      - "5050:5050"
    volumes:
      - "{{ pgadmin_data_path }}:/var/lib/pgadmin"

